### ISSUE TITLE
OsX binary release?

### ISSUE THREAD

**Issue by hiive** [dpaulat/worldengine-cpp#4]
Is there an osx binary release available?

**Comment by dpaulat** [comment]
There is no OS X binary, but it should compile with Apple Clang. I ran into dependency issues trying to build with a CI tool (binary libraries targeted for different OS X versions), but should be easily solvable. I don't have a Mac available to easily work out the issues myself.

**Comment by hiive** [comment]
I gave it a try, but I ran into the following issue.
I'm not familiar enough with conan to be able to fix this.

WARN: libgeotiff/1.7.0: requirement proj/9.0.0 overridden by gdal/3.2.1 to
proj/8.1.1
WARN: libtiff/4.3.0: requirement zlib/1.2.12 overridden by libgeotiff/1.7.0
to zlib/1.2.11
WARN: libtiff/4.3.0: requirement libdeflate/1.12 overridden by
libgeotiff/1.7.0 to libdeflate/1.8
WARN: libtiff/4.3.0: requirement libjpeg/9e overridden by libgeotiff/1.7.0
to libjpeg/9d
ERROR: Conflict in libtiff/4.3.0:
    'libtiff/4.3.0' requires 'zlib/1.2.11' while 'boost/1.76.0' requires
'zlib/1.2.12'.
    To fix this conflict you need to override the package 'zlib' in your
root package.
CMake Error at external/cmake-conan/conan.cmake:631 (message):
  Conan install failed='1'

**Comment by dpaulat** [comment]
I'm wondering if packages bumping their zlib versions to 1.2.12 broke dependency requirements.  Once conan is configured, it *should* just work.  Each of these packages are pulled from Conan Center (https://conan.io/center/). As a quick fix, you may be able to reference zlib/1.2.12 in the top level CMakeLists.txt, in the call to conan_cmake_configure under the REQUIRES directive.

https://github.com/dpaulat/worldengine-cpp/blob/9f7961aaf62db2633fc9d44b6018384812a6704e/CMakeLists.txt?plain=1#L14-L27

I did have issues building dependencies, but I made it further than what you're describing.  Here's the most recent output from CI:
https://ci.appveyor.com/project/dpaulat/worldengine-cpp/builds/39350609/job/xoian43ok275so7g

I'll take a look at this tonight, I suspect this is bigger than OS X.

**Comment by hiive** [comment]
Adding 
```
                               zlib/1.2.12
                               libiconv/1.17
```
lets me get a lot further, but I've run into another issue that I need to resolve specific to my machine before I can proceed.

Update: I had also incorporated your osx changes from the other branch, if that makes a difference.

**Comment by hiive** [comment]
It got a lot further, but the cmake error log shows the following:

```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ 
Build flags: 
Id flags:  

The output was:
1
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc 
Build flags: ;
Id flags:  

The output was:
1
ld: library not found for -lSystem
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dpaulat** [comment]
It looks like your toolchain isn't setup correctly. CMake is having trouble locating your development libraries.

**Comment by hiive** [comment]
I completely reinstalled xcode and the command line tools and I got the same error.
As far as I can tell, it's some conflict between libstdc++ and libc++, but I'm not familiar enough with the build system to figure out where it's happening.

I imagine the case is the same for the c file, but I don't know what the alternative library is in that case.

**Comment by dpaulat** [comment]
Definitely seems like a Mac thing. On appveyor, I used ninja as my CMake generator. Does that give you any different results, or are you already using ninja?

**Comment by hiive** [comment]
I'm pretty sure it's using ninja, but I'll verify tomorrow.

I can send you the entire cmake log if you think you can make sense of it, but it's been a while since I've dealt with a c++ project of this size (pre-cmake days!)

**Comment by dpaulat** [comment]
I'm happy to take a look, I can see if I can identify anywhere something might have gone wrong. I'll compare to what I setup and had executing on Appveyor.

**Comment by hiive** [comment]
Do you want me to put it here, or would you like me to send it to you via some other method?

**Comment by hiive** [comment]
Update: I got it working; I had to switch off -WError for the build of the final executable (perhaps to do with library upgrades) and I had to manually copy `libPlateTectonics.dylib` around a couple of times (once for the worldengine-test build, and again into the final bin directory), but I have an executable, so it is doable :)

**Comment by dpaulat** [comment]
Glad to hear it's working for you now. I'll work to get dependency definitions updated. If you have any other specific changes, I welcome a pull request to help others.

**Comment by hiive** [comment]
Other than the explicit tweaks I mentioned above based on your recommendation, the only other thing I did was to manually copy the lib file to where the make progress was looking for it, but if I make any further improvements, I'll be sure to do a PR.

Hopefully the info in this thread is enough for you to figure out how to fix the Mac build so that it doesn't require manual hacking!
